In [5]:
import numpy as np

i = np.array([10,20,30,40,50])

print(i.shape)

(5,)


In [6]:
i = np.array([[10,20,30,40,50],
             [60,70,80,90,100]])

print(i.shape)

(2, 5)


In [7]:
import numpy as np

i = np.array([
    [[10,20,30,40,50],[60,70,80,90,100],[60,70,80,90,100]],
    [[10,20,30,40,50],[60,70,80,90,100],[60,70,80,90,100]]
])

print(i.shape)

(2, 3, 5)


In [10]:
i = np.array([10,20,30,40,50,60,70,80,90,100])

j = i.reshape(5,2)

print(j)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [11]:
i = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

j = i.reshape(6,2)

j

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120]])

In [13]:
i = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

j = i.reshape(4,3)

j

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [19]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])

j = i.reshape(2,2,4)

j

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

In [20]:
i = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])

j = i.reshape(2,4,2)

j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [25]:
i = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])

j = i.reshape(2,4,-1)

j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [30]:


i = np.array([
    [[10,20,30],[40,50,60]],
    [[70,80,90],[100,110,120]],
    [[130,140,150],[1,2,3]]
])

j = i.reshape(-1)

j

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150,   1,   2,   3])

In [31]:
i = np.array([[10,20,30],[40,50,60],[70,80,90]])

j = i.reshape(-1)

j

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
i = np.array([10,20,30,40,50,60,70])

for j in i:
    print(j)

10
20
30
40
50
60
70


In [33]:
i = np.array([[10,20,30],[40,50,60],[70,80,90]])

for j in i:
    print(j)

[10 20 30]
[40 50 60]
[70 80 90]


In [34]:
i = np.array([[10,20,30],[40,50,60],[70,80,90]])

for j in i:
    for k in j:
        print(k)

10
20
30
40
50
60
70
80
90


In [38]:
i = np.array([
    [[10,20,30],[40,50,60],[70,80,90]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,20,30],[40,50,60],[70,80,90]]
])

for j in i:
    print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [42]:
i = np.array([
    [[10,20,30],[40,50,60],[70,80,90]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,20,30],[40,50,60],[70,80,90]]
])

for j in i:
    for k in j:
        for l in k:
            print(l)

10
20
30
40
50
60
70
80
90
1
2
3
4
5
6
7
8
9
10
20
30
40
50
60
70
80
90
